### ISSUE TITLE
Add URL to website on repo welcome page

### ISSUE THREAD

**Issue by bittner** [ungoogled-software/ungoogled-software.github.io#1]
I discovered ungoogled Chromium today, it was mentioned on the [Puri.sm forum](https://forums.puri.sm/t/ungoogled-chromium-instead-of-chromium/9093). Nice! I immediately added it to [my Ansible setup](https://github.com/painless-software/ansible-role-software/blob/master/tasks/base/webbrowsers.yml#L20-L38). :nerd_face: 

Doing research for your potential Twitter handle I found this repo. What i found missing is the URL on the [welcome page](https://github.com/ungoogled-software/ungoogled-software.github.io) (next to " Website for ungoogled-chromium").

➜ Could you configure this to https://ungoogled-software.github.io/ ?

This may sound obvious as a URL, but I guess it's just more accessible that way. :person_in_manual_wheelchair:

**Comment by Eloston** [comment]
Done :+1: 

Though I'd note the website is slightly out of date with the README in the main repo because I didn't get much feedback on it. So the README still remains the authoritative source of info.
